[build]
command = "npm config set registry https://registry.npmjs.org/ --location=project && npm install --no-fund --no-audit --legacy-peer-deps && npm run build"
publish = "dist/i-scout"

[build.environment]
NODE_VERSION = "20.11.1"
